parameters:
    wxUserClassName: WxUser

services:
    wx.message.handler:
        class: Jims\WxBundle\Model\MessageHandler
        arguments:
            - "@event_dispatcher"


    wx.event.subscriber:
        class: Jims\WxBundle\Event\WxEventSubscriber
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: kernel.event_subscriber }

    wx.user_provider:
        class: Jims\WxBundle\Security\Provider\WxUserProvider
        arguments: ['@doctrine.orm.entity_manager']

    wx.token_authenticator:
        class: Jims\WxBundle\Security\Authenticator\WxTokenAuthenticator
        arguments: [ "@doctrine.orm.entity_manager", "@wx_app" ]

    #wx.authentication.wechat_listener:
    #    class: Jims\WxBundle\Security\WechatListener
    #    arguments:
    #        - "@security.token_storage"
    #        - "@security.authentication.manager"
    #        - "@security.http_utils"
    #        - "@lilocon.wechat.sdk"
    #        - "@event_dispatcher"
    #        - "@collection"



