jims_wx:
    resource: "@JimsWxBundle/Resources/config/routing.yml"
    prefix:   /

wx_test:
    resource: "@WxTestBundle/Resources/config/routing.yml"
    prefix:   /

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /
