blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }


blog_post:
    path:     /post
    defaults: { _controller: BlogBundle:Default:post }

blog_contact:
    path:     /contact
    defaults: { _controller: BlogBundle:Default:contact }

blog_other:
    path:     /other
    defaults: { _controller: BlogBundle:Default:other }



search_data_test:
    path:     /search
    defaults: { _controller: BlogBundle:Default:testData }