<?php

namespace Jims\WxBundle\Repository;

/**
 * WxUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WxUserRepository extends \Doctrine\ORM\EntityRepository
{
}
