<?php

namespace Jims\WxBundle;

use Symfony\Bundle\SecurityBundle\DependencyInjection\SecurityExtension;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class JimsWxBundle extends Bundle
{
    public function build(ContainerBuilder $container)
    {
        parent::build($container); // TODO: Change the autogenerated stub

        /** @var SecurityExtension $extension */
        //$extension = $container->getExtension('security');
        //$extension->addSecurityListenerFactory(new WechatFactory());

    }

}
